### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by mouad47** [ivalab/grasp_multiObject_multiGrasp#19]
Traceback (most recent call last):
  File "demo_graspRGD.py", line 20, in <module>
    from model.test import im_detect
  File "/content/gdrive/My Drive/grasp_multiObject_multiGrasp/tools/../lib/model/test.py", line 20, in <module>
    from utils.cython_nms import nms, nms_new
ImportError: /content/gdrive/My Drive/grasp_multiObject_multiGrasp/tools/../lib/utils/cython_nms.so: undefined symbol: _Py_ZeroStruct

**Comment by fengyyqq** [comment]
do you resovle this question?

**Comment by fengyyqq** [comment]
do you resolve this question?
