### ISSUE TITLE
TypeError: bottleneck() argument after ** must be a mapping, not tuple

### ISSUE THREAD

**Issue by Ultraopxt** [ivalab/grasp_multiObject_multiGrasp#21]
I run :python demo_graspRGD.py --net res50 --dataset grasp, **and got an error like :**

Traceback (most recent call last):
  File "demo_graspRGD.py", line 197, in <module>
    tag='default', anchor_scales=[8, 16, 32])
  File "/content/grasp_multiObject_multiGrasp/tools/../lib/nets/network.py", line 306, in create_architecture
    rois, cls_prob, bbox_pred = self.build_network(sess, training)
  File "/content/grasp_multiObject_multiGrasp/tools/../lib/nets/resnet_v1.py", line 155, in build_network
    scope=self._resnet_scope)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py", line 207, in resnet_v1
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 215, in stack_blocks_dense
    net = block.unit_fn(net, rate=1, **unit)
**TypeError: bottleneck() argument after ** must be a mapping, not tuple**

**Comment by Soofiyan** [comment]
did you resolve this issue?

**Comment by Soofiyan** [comment]
Use google Colaboratory and install tensorflow versions 1.13.2 or more. If your device does not have Cuda installed just use google Colaboratory.

**Comment by Ultraopxt** [comment]
> Use google Colaboratory and install tensorflow versions 1.13.2 or more. If your device does not have Cuda installed just use google Colaboratory.

Thanks

**Comment by fort745** [comment]
I'm running into the same problem on my computer, are there any other workarounds besides google colab?

**Comment by siatlpl** [comment]
> Use google Colaboratory and install tensorflow versions 1.13.2 or more. If your device does not have Cuda installed just use google Colaboratory.

According to the method you said, I installed tensorflow=1.4.1, but it still did not solve

**Comment by ItsMeTheBee** [comment]
Same here, would appreciate any help =)
