### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.cython_nms'

### ISSUE THREAD

**Issue by woochen123456** [ivalab/grasp_multiObject_multiGrasp#23]
Hello, this error occurred when I was running the program, how can I solve it? Thank you! 
./tools/demo_graspRGD.py --net res50 --dataset grasp
Traceback (most recent call last):
  File "./tools/demo_graspRGD.py", line 20, in <module>
    from model.test import im_detect
  File "/home/chen/grasp_multiObject_multiGrasp/tools/../lib/model/test.py", line 20, in <module>
    from utils.cython_nms import nms, nms_new
ModuleNotFoundError: No module named 'utils.cython_nms

**Comment by ghhjklio** [comment]
Have you solved this problem? I met the same issues,thank you

**Comment by daney123** [comment]
Have you solved this problem? I met the same issues .How can I solve it
